### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by thinkmorestupidless** [akka/setup-akka-cli-action#5]
### Versions used 

@v1

### Expected Behaviour

Should work as per the documentation/example at https://doc.akka.io/operations/integrating-cicd/github-actions.html#_create_a_workflow

### Actual Behaviour

I see the following error (and the action fails)

```
Error: the Akka CLI lacks authentication (use 'akka auth login' to connect)
```

Reproducing this is easy, just ensure you're logged out of the the akka cli tool and then try to set a project 🤷 

It would appear that the refresh token needs to be set _before_ setting the project 

I've submitted a PR for this https://github.com/akka/setup-akka-cli-action/pull/4

**Comment by aludwiko** [comment]
Merged and released under v1.0.1
